# Generated by Django 3.2.6 on 2021-08-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_rename_posts_tag_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_of_completion'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
