# Generated by Django 3.2.6 on 2021-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
