# Generated by Django 3.2.6 on 2021-08-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_task_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_of_completion'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
